[env:esp32dev]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_speed = 115200
board_build.flash_mode = dio
board_build.f_flash = 40000000L

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    adafruit/Adafruit BusIO